name: Certificate Expiry Undeliverable Report

on:
  schedule:
    - cron: '10 9 * * *'

jobs:
  certificate-expiry-check:
    name: Run certificate expiry undeliverable report script
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python Packages from Requirements File
        run: |
          pip install pipenv
          pipenv install
      - name: execute certificate expiry undeliverable report run
        run: source run.sh report
        env:
          GANDI_API_KEY: ${{ secrets.GANDI_API_KEY }}
          NOTIFY_API_KEY: ${{ secrets.NOTIFY_API_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_OBJECT_NAME: ${{ secrets.S3_OBJECT_NAME }}
          EXPIRE_TEMPLATE_ID: ${{ secrets.EXPIRE_TEMPLATE_ID }}
          REPORT_TEMPLATE_ID: ${{ secrets.REPORT_TEMPLATE_ID }}
          UNDELIVERED_REPORT_TEMPLATE_ID: ${{ secrets.UNDELIVERED_REPORT_TEMPLATE_ID }}
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: 'Failed GitHub Action Run'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

