name: Stale Pull Request Check

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  check_stale_prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check for stale pull requests
      id: check_prs
      run: |
        DATE_CREATED=$(date -d '4 hours ago' --utc +%Y-%m-%dT%H:%M:%SZ)
        PR_URL=$(gh pr list --repo ${{ github.repository }} --state open --json createdAt,url,title -q ".[] | select(.createdAt < \"$DATE_CREATED\") | .url")
        if [ ! -z "$PR_URL" ]; then
          echo "STALE_PR_LINK=$PR_URL" >> $GITHUB_ENV
        else
          echo "No stale pull request found."
        fi
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Send stale pull request notification to Slack
      if: env.STALE_PR_LINK
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,message
        custom_payload: |
          {
            "text": "Stale pull request found",
            "attachments": [
              {
                "color": "#FF0000",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "Pull Request",
                    "value": "${{ env.STALE_PR_LINK }}",
                    "short": true
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}