name: Stale Pull Request Check

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 8 * * *'

jobs:
  check_stale_prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check for multiple stale pull requests
      id: check_prs
      run: |
        DATE_CREATED=$(date -d '1 minute ago' --utc +%Y-%m-%dT%H:%M:%SZ)
        PR_JSON=$(gh pr list --repo ${{ github.repository }} --state open --json createdAt,url,title -q ".[] | select(.createdAt < \"$DATE_CREATED\") | .url")

        if [ ! -z "$PR_JSON" ]; then
          echo "HAS_STALE_PRS=true" >> $GITHUB_ENV
          echo "TEMP_PR=$(echo "$PR_JSON" | tr '\n' ',')" >> $GITHUB_ENV


          echo $PR_JSON

          echo $TEMP_PR
        else
          echo "No stale pull request found."
          echo "HAS_STALE_PRS=false" >> $GITHUB_ENV
        fi
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Send stale pull request notification to Slack
      if: env.HAS_STALE_PRS == 'true'
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,message
        custom_payload: |
          {
            "text": "Stale pull request(s) found!",
            "attachments": [
              {
                "color": "#FF0000",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "Pull Request(s)",
                    "value": "${{ env.PR_JSON }} ",
                    "short": false
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}