name: Request Gandi Funds

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  request-gandi-funds:
    name: Run the check to see if more Gandi funds are needed.
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python Packages from Requirements File
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute the request gandi funds script
        run: source run.sh gandifunds
        env:
          GANDI_API_KEY: ${{ secrets.GANDI_API_KEY }}
          NOTIFY_API_KEY: ${{ secrets.NOTIFY_API_KEY }}
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: 'Failed GitHub Action Run'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
