name: unit-tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python Packages from Requirements File
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests with unittest
        run: |
          python -m unittest discover -s scripts/ -fv