name: unit-tests

on:
  pull_request:
    branches: ["main"]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python Packages from Requirements File
        run: |
          pip install pipenv
          pipenv install
      - name: Install tox
        run: pipenv install tox
      - name: Run tox
        run: pipenv run tox
